objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Behind_Milestones__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Behind Milestones</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Speaker__c</fullName>
        <label>Lead Speaker</label>
        <referenceTo>Session_Speaker__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>SES-{0000}</displayFormat>
        <label>Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Session_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Completed__c</fullName>
        <label>Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>Milestone__c</referenceTo>
        <relationshipLabel>Session Milestones</relationshipLabel>
        <relationshipName>Session_Milestones</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Session Milestones</relationshipLabel>
        <relationshipName>Session_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Milestone</label>
    <nameField>
        <displayFormat>SSM-{0000}</displayFormat>
        <label>Session Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Session_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Lead_Speaker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Speaker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Sessions Speakers</relationshipLabel>
        <relationshipName>Sessions_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Session Speaker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DataUtility.cls
public with sharing class DataUtility {
	public DataUtility() {	}
	
	public static void createMilestoneData() {
		List<Milestone__c> milestones = new List<Milestone__c>();
		milestones.add(new Milestone__c(Name='Title Approved', Deadline__c=date.parse('1/2/2013')));
		milestones.add(new Milestone__c(Name='Abstract Approved', Deadline__c=date.parse('11/3/2013')));
		milestones.add(new Milestone__c(Name='Speakers Approved', Deadline__c=date.parse('11/4/2013')));
		milestones.add(new Milestone__c(Name='Slides Drafted', Deadline__c=date.parse('11/5/2013')));
		milestones.add(new Milestone__c(Name='Dry Run Scheduled', Deadline__c=date.parse('11/6/2013')));
		milestones.add(new Milestone__c(Name='Dry Run Approved', Deadline__c=date.parse('11/7/2013')));
		milestones.add(new Milestone__c(Name='Slides Approved', Deadline__c=date.parse('11/8/2013')));
		
		insert milestones;
	}
	
	public static List<Session__c> checkMilestones(List<Session__c> scope) {
		Date t = Date.Today();	
		Map<Id,Session__c> mapped_sessions = new Map<Id,Session__c>(scope);
		for(Session__c s : scope) {
			s.Behind_Milestones__c = false; //assume the session is not behind
		}
		Map<Id, Session_Milestone__c> milestones = new Map<Id, Session_Milestone__c>([SELECT Id,Session__c from Session_Milestone__c WHERE Session__c IN :mapped_sessions.keyset() AND Completed__c = NULL AND Milestone__r.Deadline__c <= :t]);
		for(Id milestone_id : milestones.keySet()) {
			mapped_sessions.get(milestones.get(milestone_id).Session__c).Behind_Milestones__c = true; //failed milestone found
			}
		
		
		return scope;
	}
	
	
	public static List<Session_Milestone__c> createMilestonesFor(Session__c s) {
		List<Session_Milestone__c> session_milestones = new List<Session_Milestone__c>();
		List<Milestone__c> existing_milestones = [SELECT ID from Milestone__c];
		for(Milestone__c m : existing_milestones) {
			session_milestones.add(new Session_Milestone__c(Session__c=s.Id,Milestone__c=m.Id));
		}
		
		return session_milestones;
	}
	
	public static List<Session_Speaker__c> checkDuplicateLeadSpeakers(List<Session_Speaker__c> scope) {
		List<Id> session_ids = new List<Id>();
		List<Session_Speaker__c> dupe_leads = new List<Session_Speaker__c>();
		Map<Id,Session_Speaker__c> lead_speakers = new Map<Id,Session_Speaker__c>();
	
		for(Session_Speaker__c s : scope) {
			if(s.Lead_Speaker__c == true) {
				session_ids.add(s.Session__c);
				if(s.Id != null) {lead_speakers.put(s.Id,s);}	
		}
		
		
		List<Session_Speaker__c> duplicate_leads = [SELECT ID from Session_Speaker__c WHERE ID NOT IN :lead_speakers.keySet() AND Session__c IN :session_ids AND Lead_Speaker__c = TRUE];
		for(Session_Speaker__c speaker : scope) {
				for(Session_Speaker__c dupe : duplicate_leads) {
					if(dupe.Session__c == speaker.Session__c) {
						dupe_leads.add(speaker);
					}
				}
			}
		
		
		}
	
		return dupe_leads;
	
	}
	
	
	

}