objects/Session_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Speaker__c</fullName>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Sessions Speakers</relationshipLabel>
        <relationshipName>Sessions_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Session Speaker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PortalHandler.cls
global with sharing class PortalHandler implements Auth.RegistrationHandler{
	
		global User createUser(Id portalId, Auth.UserData data){
		    User u = new User();
		    Profile p = [SELECT Id FROM profile WHERE name='DFC Speaker'];
		    u.username = data.username;
			System.debug(u.username);
		    u.email = data.email;
		    u.lastName = data.lastName;
		    u.firstName = data.firstName;
		    String alias = data.username;
		    if(alias.length() > 8) {
		        alias = alias.substring(0, 8);
		    }
		    u.alias = alias;
		    u.languagelocalekey = data.locale;
		    u.localesidkey = data.locale;
		    u.emailEncodingKey = 'UTF-8';
		    u.timeZoneSidKey = 'America/Los_Angeles';
		    u.profileId = p.Id;
			System.debug(u.profileId);

		    return u;
		}

		global void updateUser(Id userId, Id portalId, Auth.UserData data){}

		global static void sendSpeakerApprovalEmail(List<Speaker__c> speakers) {
	
		}

		global static void sendSessionApprovalEmail(List<Session_Speaker__c> speakers) {
	
		}

}