objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Abstract__c</fullName>
        <label>Abstract</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Additional_Details__c</fullName>
        <label>Additional Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lead_Speaker__c</fullName>
        <label>Lead Speaker</label>
        <referenceTo>Session_Speaker__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>SES-{0000}</displayFormat>
        <label>Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Session_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Lead_Speaker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Speaker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Sessions Speakers</relationshipLabel>
        <relationshipName>Sessions_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Sessions Speakers</relationshipLabel>
        <relationshipName>Sessions_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Session Speaker ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CFPREST.cls
@RestResource(urlMapping='/papers/*')
global with sharing class CFPREST {

	global CFPREST() {}
	
	//{"data":{"FirstName": "Joe","LastName": "Smith","MobilePhone": "888-888-8888","Bio": "One Cool Guy","Email": "joe@smith.com","Title": "My Session","SessionAbstract": "is so cool"}}	
	@HTTPPost
	global static FormStatus submitPaper(FormData data) {
		Speaker__c speaker = new Speaker__c(First_Name__c=data.FirstName,Last_Name__c=data.LastName,Mobile_Phone__c=data.MobilePhone,Position__c=data.Position,Company__c=data.Company,Email__c=data.Email,Twitter__c=data.Twitter,Bio__c=data.Bio);
		
		List<Speaker__c> existing_speakers = [SELECT ID from Speaker__c WHERE Email__c =: data.Email];
		if(existing_speakers.size() == 0) {
			//speaker does not exist, attempt to create one
			try {
				insert speaker;
			} catch(DMLException e) {
				FormStatus fs = new FormStatus();
				fs.Status = 'Error';
				fs.Message = e.getMessage();
			
				return fs;
			}
			
		} else {
			speaker.Id = existing_speakers[0].Id;
		}
		
		Session__c session = new Session__c(Title__c=data.Title,Abstract__c=data.SessionAbstract,Additional_Details__c=data.Notes);
		try {
			insert session;
		} catch(DMLException e) {
			FormStatus fs = new FormStatus();
			fs.Status = 'Error';
			fs.Message = e.getMessage();
			
			return fs;
		}
		
		Session_Speaker__c ss = new Session_Speaker__c(Session__c=session.Id,Speaker__c=speaker.Id,Lead_Speaker__c=true);
		try {
			insert ss;
		} catch(DMLException e) {
			FormStatus fs = new FormStatus();
			fs.Status = 'Error';
			fs.Message = e.getMessage();
			
			return fs;
		}
		
		FormStatus fs = new FormStatus();
		fs.Status = 'Completed';
		fs.Message = 'Submission complete. Speaker:'+speaker.Id+' Session:'+session.Id;
		
		return fs;
	}	
	
	
	
	global class FormData {
    //Speaker Data
        global String FirstName { get; set; }
        global String LastName { get; set; }
        global String MobilePhone { get; set; }
        global String Position { get; set; }
        global String Company { get; set; }
		global String Email { get; set; }
		global String Twitter { get; set; }
		global String Bio { get; set; }
		
	//Session Data
		global String Title { get; set; }
        global String SessionAbstract { get; set; }
        global String Notes { get; set; }
	}	
	
	global class FormStatus {
		global String Status { get; set; }
        global String Message { get; set; }
	}

}